<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/auth.proto

namespace App\Grpc\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.v1.GoogleLoginRequest</code>
 */
class GoogleLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id_token = 1;</code>
     */
    protected $id_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id_token
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\Auth\V1\GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id_token = 1;</code>
     * @return string
     */
    public function getIdToken()
    {
        return $this->id_token;
    }

    /**
     * Generated from protobuf field <code>string id_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->id_token = $var;

        return $this;
    }

}

